# Generated by Django 4.1.6 on 2023-03-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color'), ('images', 'images')], default='size', max_length=6),
        ),
    ]
